/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:52 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFPreferenceObserver : NSObject {

	/*^block*/id _callback;

}

@property (copy) id callback;              //@synthesize callback=_callback - In the implementation block
-(void)dealloc;
-(void)stop;
-(void)start;
-(void)setCallback:(id)arg1 ;
-(id)callback;
-(void)updateDiagnosticLogging;
-(void)handlePreferencesChanged;
-(void)handleProfilesChanged;
@end

