/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:52 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libextension.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PKModularService <NSObject>
@optional
-(void)beginUsing:(id)arg1 withBundle:(id)arg2;
-(void)endUsing:(id)arg1;
-(void)communicationsFailed:(id)arg1;

@required
+(id)initForPlugInKit;

@end

