/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString, NSNumber;


@protocol ACMBaseAuthenticationRequest <NSObject>
@property (retain) NSString * realm; 
@property (retain) NSString * userName; 
@property (retain) NSNumber * appID; 
@property (retain) NSString * appIDKey; 
@property (retain) NSNumber * serverResponseTimeout; 
@required
-(NSString *)userName;
-(void)setAppID:(id)arg1;
-(void)setRealm:(id)arg1;
-(void)setUserName:(id)arg1;
-(NSString *)realm;
-(void)setAppIDKey:(id)arg1;
-(NSNumber *)appID;
-(NSString *)appIDKey;
-(NSNumber *)serverResponseTimeout;
-(void)setServerResponseTimeout:(id)arg1;

@end

