/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMHTTPHandler.h>

@class ACMTicketVerificationRequestImpl;

@interface ACMHTTPTicketVerificationHandler : ACMHTTPHandler {

	ACMTicketVerificationRequestImpl* _request;

}

@property (retain) ACMTicketVerificationRequestImpl * request;              //@synthesize request=_request - In the implementation block
+(id)handlerWithRequest:(id)arg1 ;
-(void)dealloc;
-(ACMTicketVerificationRequestImpl *)request;
-(id)requestBody;
-(void)setRequest:(ACMTicketVerificationRequestImpl *)arg1 ;
@end

