/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACMProvisionManagerProtocol <NSObject>
@required
-(id)publicKeyVersionForRealm:(id)arg1;
-(SecKeyRef)publicKeyForRealm:(id)arg1;
-(void)clearPublicKeyForRealm:(id)arg1;
-(SecIdentityRef)deviceIdentityForRealm:(id)arg1;
-(id)deviceIdentityCertificatesForRealm:(id)arg1;
-(void)clearDeviceIdentityForRealm:(id)arg1;
-(BOOL)isDeviceIdentityValidForRealm:(id)arg1;
-(SecCertificateRef)defaultPublicKeyCertificateForRealm:(id)arg1;
-(id)defaultPublicKeyVersionForRealm:(id)arg1;
-(BOOL)setPublicKeyWithCertificate:(SecCertificateRef)arg1 version:(id)arg2 forRealm:(id)arg3;

@end

