/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:50 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMSignInDialogSimple.h>

@interface ACMSignInDialogSimple_Modern : ACMSignInDialogSimple {

	double _backgroundHorizontalParallaxValue;
	double _backgroundVerticalParallaxValue;

}
-(void)setBackgroundColor:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)backgroundColor;
-(void)dealloc;
-(id)init;
-(void)didReceiveMemoryWarning;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(id)cancelButton;
-(void)updateViewConstraints;
-(id)imageView;
-(id)passwordField;
-(id)accountNameField;
-(id)loginButton;
-(void)setupBackgroundViewIfNeeded;
-(void)setupParallaxParameters;
-(void)setParallaxEffectForView:(id)arg1 ;
-(void)setupView;
-(void)centerHorizontallyView:(id)arg1 relativeToView:(id)arg2 ;
-(id)buttonsContainerView;
-(id)defaultBackgroundPatternImage;
@end

