/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/ACMSystemInfoProtocol.h>

@interface ACMSystemInfo : NSObject <ACMSystemInfoProtocol>
-(id)systemVersion;
-(id)deviceModel;
-(id)uniqueDeviceIdentifier;
-(id)MACAddress;
-(id)IPAddress;
-(BOOL)isRunningOnModernMobileSystem;
-(id)randomBytesWithSize:(unsigned long long)arg1 ;
@end

