/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class ACMExternalAuthenticationRequestImpl, NSString;


@protocol ACMSignInDialogProtocol <NSObject>
@property (assign) id<ACMSignInDialogDelegate> delegate; 
@property (retain) ACMExternalAuthenticationRequestImpl * request; 
@property (readonly) NSString * passwordString; 
@required
-(void)setDelegate:(id)arg1;
-(id<ACMSignInDialogDelegate>)delegate;
-(ACMExternalAuthenticationRequestImpl *)request;
-(NSString *)passwordString;
-(void)setRequest:(id)arg1;
-(void)showWithParentViewController:(id)arg1 animated:(BOOL)arg2;
-(void)hideWithParentViewController:(id)arg1 animated:(BOOL)arg2;

@end

