/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSNumber, NSDictionary, NSError;


@protocol ACMTicketVerificationResponse <NSObject>
@property (retain,readonly) NSNumber * personDSID; 
@property (retain,readonly) NSDictionary * rawResponseData; 
@property (retain,readonly) NSError * error; 
@property (retain,readonly) id userInfo; 
@required
-(NSError *)error;
-(id)userInfo;
-(NSDictionary *)rawResponseData;
-(NSNumber *)personDSID;

@end

