/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:50 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTDataProviderProtocol <NSObject>
@optional
-(void)purgeCache;
-(void)refresh;

@required
+(id)providerName;
-(void)populateDataProviderWithHandler:(/*^block*/id)arg1;
-(BOOL)supportsEventClass:(Class)arg1;
-(id)supportedEventClasses;

@end

