/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:50 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTDaemonInternalProtocol <NSObject>
@required
-(void)forceSequentialClusterIdentification:(/*^block*/id)arg1;
-(void)injectLocationOfInterest:(id)arg1 reply:(/*^block*/id)arg2;
-(void)removeLocationOfInterest:(id)arg1 reply:(/*^block*/id)arg2;
-(void)injectVisit:(id)arg1 locationOfInterest:(id)arg2 reply:(/*^block*/id)arg3;
-(void)removeVisit:(id)arg1 locationOfInterest:(id)arg2 reply:(/*^block*/id)arg3;
-(void)fetchPredictedApplicationForEvent:(id)arg1 withReply:(/*^block*/id)arg2;
-(void)processDataForPredictionModelWithReply:(/*^block*/id)arg1;
-(void)printMagicalMomentsModelWithReply:(/*^block*/id)arg1;
-(void)forceUpdateAssetMetadata;

@end

