/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:52 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class RTEvent;

@interface RTDataProviderNotificationRealtime : RTNotification {

	RTEvent* _event;

}

@property (nonatomic,readonly) RTEvent * event;              //@synthesize event=_event - In the implementation block
-(id)initWithEvent:(id)arg1 ;
-(RTEvent *)event;
@end

