/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:51 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface RTDuetHelperRecord : NSObject {

	NSString* _notificationName;
	/*^block*/id _eventReceivedBlock;

}

@property (nonatomic,retain) NSString * notificationName;              //@synthesize notificationName=_notificationName - In the implementation block
@property (nonatomic,copy) id eventReceivedBlock;                      //@synthesize eventReceivedBlock=_eventReceivedBlock - In the implementation block
-(NSString *)notificationName;
-(id)initWithNotificationName:(id)arg1 eventReceivedBlock:(/*^block*/id)arg2 ;
-(void)setNotificationName:(NSString *)arg1 ;
-(id)eventReceivedBlock;
-(void)setEventReceivedBlock:(id)arg1 ;
@end

