/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:50 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramInstance;

@interface RTMetricMagicalMomentRecommendation : NSObject {

	AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramInstance* _metric;
	double _confidence;

}

@property (nonatomic,readonly) AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramInstance * metric;              //@synthesize metric=_metric - In the implementation block
@property (nonatomic,readonly) double confidence;                                                                  //@synthesize confidence=_confidence - In the implementation block
-(double)confidence;
-(AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramInstance *)metric;
-(id)initWithMetric:(id)arg1 confidence:(double)arg2 ;
@end

