/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:51 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTMotionActivityManagerNotificationVehicleConnected : RTNotification {

	unsigned long long _vehicleConnectedState;

}

@property (nonatomic,readonly) unsigned long long vehicleConnectedState;              //@synthesize vehicleConnectedState=_vehicleConnectedState - In the implementation block
+(id)notificationName;
-(id)initWithVehicleConnectedState:(unsigned long long)arg1 ;
-(unsigned long long)vehicleConnectedState;
@end

