/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:51 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class GEONavigationListener, GEONavigationRouteSummary;

@interface RTNavigationManager : RTNotifier {

	BOOL _monitorRouteSummary;
	GEONavigationListener* _navigationListener;
	GEONavigationRouteSummary* _routeSummary;

}

@property (nonatomic,retain) GEONavigationListener * navigationListener;              //@synthesize navigationListener=_navigationListener - In the implementation block
@property (assign,nonatomic) BOOL monitorRouteSummary;                                //@synthesize monitorRouteSummary=_monitorRouteSummary - In the implementation block
@property (nonatomic,retain) GEONavigationRouteSummary * routeSummary;                //@synthesize routeSummary=_routeSummary - In the implementation block
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(GEONavigationRouteSummary *)routeSummary;
-(void)setup;
-(void)onAuthorizationNotification:(id)arg1 ;
-(GEONavigationListener *)navigationListener;
-(void)setRouteSummary:(GEONavigationRouteSummary *)arg1 ;
-(void)setMonitorRouteSummary:(BOOL)arg1 ;
-(void)setNavigationListener:(GEONavigationListener *)arg1 ;
-(BOOL)monitorRouteSummary;
@end

