/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:51 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTPredictionModelDelegate <NSObject>
@optional
-(void)predictionModelWillStartProcessingData:(id)arg1;
-(void)predictionModelDidFinishProcessingData:(id)arg1;
-(void)predictionModelDidBecomeInvalid:(id)arg1;
-(void)predictionModel:(id)arg1 receivedError:(id)arg2;

@required
-(id)dataProviderForName:(id)arg1;
-(id)predictionModel:(id)arg1 dataProviderAtIndex:(unsigned long long)arg2;
-(unsigned long long)countOfDataProviders;

@end

