/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:52 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class RTScenarioTrigger;

@interface RTScenarioTriggerNotification : RTNotification {

	RTScenarioTrigger* _scenarioTrigger;

}

@property (nonatomic,retain,readonly) RTScenarioTrigger * scenarioTrigger;              //@synthesize scenarioTrigger=_scenarioTrigger - In the implementation block
+(id)notificationName;
-(RTScenarioTrigger *)scenarioTrigger;
-(id)initWithScenarioTrigger:(id)arg1 ;
@end

