/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libCTLogHelper.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct shared_ptr<CTLogHelperController> {
	CTLogHelperController __ptr_;
	__shared_weak_count __cntrl_;
} shared_ptr<CTLogHelperController>;

