/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:53 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	int field1;
	char field2;
	char field3;
	char field4;
	char field5;
	double field6;
} SCD_Struct_NS1;

typedef struct {
	char* field1;
	unsigned long long field2;
} SCD_Struct_NS2;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct __CFString* CFStringRef;

