/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:53 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface OS_object : NSObject
-(void)_dispose;
-(id)retain;
-(oneway void)release;
-(unsigned long long)retainCount;
-(BOOL)allowsWeakReference;
-(BOOL)retainWeakReference;
-(void)_xref_dispose;
@end

