/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:53 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/system/libxpc.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libxpc.dylib/OS_xpc_object.h>
#import <libobjc.A.dylib/OS_xpc_mach_send.h>

@protocol OS_xpc_mach_send <OS_xpc_object>
@end


@class NSString;

@interface OS_xpc_mach_send : OS_xpc_object <OS_xpc_mach_send>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)load;
@end

