/*
* This header is generated by classdump-dyld 1.0
* on Friday, March 18, 2016 at 1:49:49 AM Central Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libTelephonyUtilDynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct weak_ptr<ctu::Http::URLConnectionCallbackHandler> {
	URLConnectionCallbackHandler __ptr_;
	__shared_weak_count __cntrl_;
} weak_ptr<ctu::Http::URLConnectionCallbackHandler>;

typedef struct shared_ptr<ctu::Http::HttpResponse> {
	HttpResponse __ptr_;
	__shared_weak_count __cntrl_;
} shared_ptr<ctu::Http::HttpResponse>;

